"""
This type stub file was generated by pyright.
"""

import math  # type: ignore
import string  # type: ignore
import sys  # type: ignore
import warnings  # type: ignore
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    Dict,
    Iterable,
    Iterator,  # type: ignore
    List,
    Optional,
    Set,
    Tuple,
    Type,
    TypeVar,
    Union,
    cast,  # type: ignore
    no_type_check,
)
from faker.typing import BasicNumber
from ...exceptions import BaseFakerException
from .. import BaseProvider, ElementsType  # type: ignore

TypesNames = List[str]
TypesSpec = Union[List[Type], Tuple[Type, ...]]  # type: ignore
TEnum = TypeVar("TEnum", bound=Enum)

class EmptyEnumException(BaseFakerException): ...

class Provider(BaseProvider):
    default_value_types: ElementsType[str] = ...
    def pyobject(
        self,
        object_type: Optional[  # type: ignore
            Type[Union[bool, str, float, int, tuple, set, list, Iterable, dict]]  # type: ignore
        ] = ...,
    ) -> Optional[Union[bool, str, float, int, tuple, set, list, Iterable, dict]]:  # type: ignore
        """
        Generates a random object passing the type desired.

        :object_type: the type of the object to generate.
        :return: the random object generated.
        :raises ValueError: if the object type passed is not supported
        """
        ...

    def pybool(self, truth_probability: int = ...) -> bool:
        """
        Generates a random boolean, optionally biased towards `True` or `False`.

        :truth_probability: Probability of generating a `True` value. Must be between `0` and `100` inclusive'.
        :return: Random boolean.
        :raises ValueError: If invalid `truth_probability` is provided.
        """
        ...

    def pystr(
        self,
        min_chars: Optional[int] = ...,
        max_chars: int = ...,
        prefix: str = ...,
        suffix: str = ...,
    ) -> str:
        """
        Generates a random string of upper and lowercase letters.

        :param min_chars: minimum length of the random part.
        :param max_chars: maximum length of the random part.
        :param prefix: an optional prefix to prepend to the random string.
        :param suffix: an optional suffix to append to the random string.
        :return: Random of random length between min and max characters.
        """
        ...

    def pystr_format(self, string_format: str = ..., letters: str = ...) -> str: ...
    @no_type_check
    def pyfloat(
        self,
        left_digits: Optional[int] = ...,
        right_digits: Optional[int] = ...,
        positive: Optional[bool] = ...,
        min_value: Optional[Union[float, int]] = ...,
        max_value: Optional[Union[float, int]] = ...,
    ) -> float: ...
    def pyint(
        self, min_value: int = ..., max_value: int = ..., step: int = ...
    ) -> int: ...
    def pydecimal(
        self,
        left_digits: Optional[int] = ...,
        right_digits: Optional[int] = ...,
        positive: Optional[bool] = ...,
        min_value: Optional[BasicNumber] = ...,
        max_value: Optional[BasicNumber] = ...,
    ) -> Decimal: ...
    def pytuple(
        self,
        nb_elements: int = ...,
        variable_nb_elements: bool = ...,
        value_types: Optional[TypesSpec] = ...,  # type: ignore
        allowed_types: Optional[TypesSpec] = ...,  # type: ignore
    ) -> Tuple[Any, ...]: ...
    def pyset(
        self,
        nb_elements: int = ...,
        variable_nb_elements: bool = ...,
        value_types: Optional[TypesSpec] = ...,  # type: ignore
        allowed_types: Optional[TypesSpec] = ...,  # type: ignore
    ) -> Set[Any]: ...
    def pylist(
        self,
        nb_elements: int = ...,
        variable_nb_elements: bool = ...,
        value_types: Optional[TypesSpec] = ...,  # type: ignore
        allowed_types: Optional[TypesSpec] = ...,  # type: ignore
    ) -> List[Any]: ...
    @no_type_check
    def pyiterable(
        self,
        nb_elements: int = ...,
        variable_nb_elements: bool = ...,
        value_types: Optional[TypesSpec] = ...,
        allowed_types: Optional[TypesSpec] = ...,
    ) -> Iterable[Any]: ...
    def pydict(
        self,
        nb_elements: int = ...,
        variable_nb_elements: bool = ...,
        value_types: Optional[TypesSpec] = ...,  # type: ignore
        allowed_types: Optional[TypesSpec] = ...,  # type: ignore
    ) -> Dict[Any, Any]:
        """
        Returns a dictionary.

        :nb_elements: number of elements for dictionary
        :variable_nb_elements: is use variable number of elements for dictionary
        :value_types: type of dictionary values
        """
        ...

    def pystruct(
        self,
        count: int = ...,
        value_types: Optional[TypesSpec] = ...,  # type: ignore
        allowed_types: Optional[TypesSpec] = ...,  # type: ignore
    ) -> Tuple[List, Dict, Dict]: ...  # type: ignore
    def enum(self, enum_cls: Type[TEnum]) -> TEnum:
        """
        Returns a random enum of the provided input `Enum` type.

        :param enum_cls: The `Enum` type to produce the value for.
        :returns: A randomly selected enum value.
        """
        ...
