"""
This type stub file was generated by pyright.
"""

from io import TextIOWrapper
from typing import Dict, List, Optional, TextIO, TypeVar, Union
from .documentor import Documentor
from .providers import BaseProvider

__author__ = ...
T = TypeVar("T")

def print_provider(
    doc: Documentor,
    provider: BaseProvider,
    formatters: Dict[str, T],
    excludes: Optional[List[str]] = ...,
    output: Optional[TextIO] = ...,
) -> None: ...
def print_doc(
    provider_or_field: Optional[str] = ...,
    args: Optional[List[T]] = ...,
    lang: str = ...,
    output: Optional[Union[TextIO, TextIOWrapper]] = ...,
    seed: Optional[float] = ...,
    includes: Optional[List[str]] = ...,
) -> None: ...

class Command:
    def __init__(self, argv: Optional[str] = ...) -> None: ...
    def execute(self) -> None:
        """
        Given the command-line arguments, this creates a parser appropriate
        to that command, and runs it.
        """
        ...

def execute_from_command_line(argv: Optional[str] = ...) -> None:
    """A simple method that runs a Command."""
    ...

if __name__ == "__main__": ...
