"""
This type stub file was generated by pyright.
"""

from enum import Enum, auto
from typing import Any, Dict, List, Optional, Tuple, Union
from .generator import Generator
from .providers import BaseProvider
from .proxy import Faker

class FakerEnum(Enum):
    """Required for faker.providers.enum"""

    A = auto
    B = auto

class Documentor:
    def __init__(self, generator: Union[Generator, Faker]) -> None:
        """
        :param generator: a localized Generator with providers filled,
                          for which to write the documentation
        :type generator: faker.Generator()
        """
        ...

    def get_formatters(
        self,
        locale: Optional[str] = ...,
        excludes: Optional[List[str]] = ...,
        **kwargs: Any,
    ) -> List[Tuple[BaseProvider, Dict[str, str]]]: ...
    def get_provider_formatters(
        self,
        provider: BaseProvider,
        prefix: str = ...,
        with_args: bool = ...,
        with_defaults: bool = ...,
    ) -> Dict[str, str]: ...
    @staticmethod
    def get_provider_name(provider_class: BaseProvider) -> str: ...
