"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from .generator import Generator

logger = ...
inREPL = ...
if inREPL: ...
else: ...

class Factory:
    @classmethod
    def create(
        cls,
        locale: Optional[str] = ...,
        providers: Optional[List[str]] = ...,
        generator: Optional[Generator] = ...,
        includes: Optional[List[str]] = ...,
        use_weighting: bool = ...,
        **config: Any,
    ) -> Generator: ...
