"""
This type stub file was generated by pyright.
"""

import dataclasses
from datetime import date, datetime, timedelta
from decimal import Decimal
from typing import List, Literal, Sequence, TypeVar, Union

class CreditCard:
    def __init__(
        self,
        name: str,
        prefixes: List[str],
        length: int = ...,
        security_code: str = ...,
        security_code_length: int = ...,
    ) -> None: ...

BasicNumber = Union[float, int, Decimal]
CardType = TypeVar("CardType", "CreditCard", str)
DateParseType = Union[date, datetime, timedelta, str, int]
HueType = Union[str, float, int, Sequence[int]]
SexLiteral = Literal["M", "F", "X"]
SeedType = Union[int, float, str, bytes, bytearray, None]

@dataclasses.dataclass
class Country:
    name: str
    timezones: Sequence[str]
    alpha_2_code: str
    alpha_3_code: str
    continent: str
    capital: str
    ...

__all__ = [
    "OrderedDictType",  # type: ignore
    "CreditCard",
    "CardType",
    "Country",
    "DateParseType",
    "HueType",
    "SexLiteral",
    "SeedType",
]
