@startuml

left to right direction

actor "Car Driver"
actor "Payment Service"
actor "System Clock"

usecase "Buy Ticket"
"Car Driver" --> "Buy Ticket"
"Buy Ticket" --> "Payment Service"
"Buy Ticket" --> "System Clock"

usecase "Check Car"
"Parking Inspector" --> "Check Car"
"Check Car" --> "System Clock"
Administrator --> (Define Parking Rates)

@enduml
